[project]
authors = ["Roy Wright <roy@wright.org>"]
channels = ["freecad/label/dev", "conda-forge"]
description = "Manages FreeCAD varsets and aliases"
name = "freecad.datamanager_wb"
platforms = ["osx-arm64", "linux-aarch64", "linux-64", "win-64", "osx-64"]
version = "0.1.0"

[pypi-dependencies]
freecad_datamanager_wb = { path = ".", editable = true }

[tasks]
test = "python tests/tests.py"

[dependencies]
freecad = ">=1.0.0,<2"